#pragma once
enum tokentypes {
	TEOF, TCONST, TELSE, TIF, TINT, TFLOAT, TCHAR, TSTRING, TRETURN, TVOID, TWHILE, TMAIN, TPRINT, TPLUS, TMINUS, TMUL, TDIV, TMOD, TASSIGN, TADDASSIGN, TSUBASSIGN, TMULASSIGN, TDIVASSIGN, TMODASSIGN, TNOT, TAND, TOR, TEQUAL, TNOTEQU, TLESS, TGREAT, TLESSE, TGREATE, TINC, TDEC, TLPAREN, TRPAREN, TDOT, TCOMMA, TLBRACE, TRBRACE, TLBRACKET, TRBRACKET, TSEMICOLON, TQUOTE, TIDENT, TINTNUM, TFLOATNUM, TERROR1, TERROR2, TERROR3, LINEPROCESS

};