#pragma once
enum tokentypes { TEOF, TCONST, TELSE, TIF, TINT, TRETURN, TVOID, TWHILE, TEQUAL, 
	TNOTEQU, TLESS, TGREAT, TAND, TOR, TINC, TDEC, TADDASSIGN, TSUBASSIGN, 
	TMULASSIGN, TDIVASSIGN, TMODASSIGN, TPLUS, TMINUS, TSTAR, TSLASH, TMOD, 
	TASSIGN, TIDENT, TNUMBER, TERROR, LINEPROCESS };